ernadoo_mondial_relay:
    api:
        wsdl: https://api.mondialrelay.com/Web_Services.asmx?WSDL
        options:
            trace: '%kernel.debug%'
            #keep_alive : false
            #cache_wsdl : !php/const WSDL_CACHE_NONE

        credentials:
            customer_code:
            secret_key:
            brand_id: